[phases.setup]
nixPkgs = ["nodejs-18_x", "git-lfs"]

[phases.install]
dependsOn = ["setup"]
cmds = ["git lfs install --skip-repo && git lfs pull || true", "npm install"]

[start]
cmd = "npm run start"
