[phases.setup]
nixPkgs = ["stdenv", "gcc", "nodejs-18_x"]
cmds = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y",
    "source $HOME/.cargo/env",
    "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && npm install"]

[phases.build]
dependsOn = ["install"]
cmds = [
    "source $HOME/.cargo/env",
    "cd backend/rust-bls-engine && wasm-pack build --target nodejs --out-dir ../src/pkg"
]

[start]
cmd = "cd backend && npm run start"
